export const books = [
  {
    id: 1,
    book_name: "세계사 익스프레스",
    author: "김영석",
    publisher: "빅피시",
    total_amount: 5,
    total_rented: 0,
  },
  {
    id: 2,
    book_name: "총균쇠",
    author: "제레드 다이아몬드",
    publisher: "김영사",
    total_amount: 10,
    total_rented: 0,
  },
  {
    id: 3,
    book_name: "Do it! 자바스크립트",
    author: "정인용",
    publisher: "이지스퍼블리싱",
    total_amount: 7,
    total_rented: 0,
  },
  {
    id: 4,
    book_name: "불편한 편의점",
    author: "김호연",
    publisher: "나무옆의자",
    total_amount: 8,
    total_rented: 0,
  },
  {
    id: 5,
    book_name: "면역다이어트",
    author: "김사랑",
    publisher: "카시오페아",
    total_amount: 3,
    total_rented: 0,
  },
];
